# Generated by Django 4.2.9 on 2024-01-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplicationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looking_for', models.CharField(choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Top Level', 'Top Level')], max_length=20)),
                ('present_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_job_categor', models.CharField(max_length=100)),
                ('preferred_district', models.CharField(max_length=100)),
                ('preferred_ogranization_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('Mother_Name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated')], max_length=100)),
                ('nationality', models.CharField(choices=[('Bangladeshi', 'Bangladeshi'), ('Other', 'Other Country')], max_length=40)),
                ('passport', models.CharField(max_length=20)),
                ('nid', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv_pdfs/')),
            ],
        ),
    ]
