# Generated by Django 4.2.9 on 2024-01-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0003_experienceinformationthree_experienceinformationtwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_training', models.CharField(max_length=100)),
                ('training_institute', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
    ]
