# Generated by Django 4.2.9 on 2024-01-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0004_traininginformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
            ],
        ),
    ]
