# Generated by Django 4.2.9 on 2024-01-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0005_contactinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininginformation',
            name='training_institute',
            field=models.TextField(max_length=100),
        ),
    ]
