# Generated by Django 4.2.9 on 2024-01-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0007_reference1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('primary_mobile_number', models.CharField(max_length=15)),
                ('primary_email', models.EmailField(max_length=254)),
                ('relation', models.CharField(max_length=50)),
            ],
        ),
    ]
